# This config file is compatible with the ES-DE Emulation Frontend
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed

exclude:
  roms:
    single_file:
      extensions:
        - "xml"
        - "txt"
      names:
        - "info.txt"
        - "metadata.txt"
        - "systeminfo.txt"
        - "psy.ggjud.iso"
        - "psy.ggjud.nfo"
    multi_file:
      names:
        - "roms"
        - "pfx"
        - "mlc01"
        - ".Trash*"

system:
  platforms:
    n3ds: "3ds"
    astrocde: "astrocade"
    apfm1000: "apf"
    atarijaguarcd: "jaguarcd"
    atari800: "atari8bit"
    crvision: "creativision"
    atarijaguar: "jaguar"
    atarilynx: "lynx"
    macintosh: "mac"
    neogeo: "neogeoaes"
    gc: "ngc"
    palm: "palmos"
    mastersystem: "sms"
    megacd: "segacd"
    sfc: "sfam"
    sg-1000: "sg1000"
    trs-80: "trs80"
    tg-cd: "pcenginecd"
    tg16: "pcengine"
    vic20: "c20"
    videopac: "videopacplus"
    pc: "win"
    zmachine: "z-machine"
    zxspectrum: "zxs"
    naomi: "arcade"
    naomi2: "arcade"
    naomigd: "arcade"
