# This config file is compatible with Batocera or Retrobat-based set-ups
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names: []
filesystem: {}
system:
  platforms:
    adam: colecoadam
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacdtv: amigacd32
    astrocde: astrocade
    apfm1000: apf
    archimedes: acorn-archimedes
    atari800: atari
    atomiswave: arcade
    bbc: bbcmicro
    c20: vic-20
    camplynx: camputers-lynx
    cdi: philips-cd-i
    channelf: fairchild-channel-f
    coco: trs-80-color-computer
    cplus4: c-plus-4
    crvision: creativision
    dreamcast: dc
    easyrpg: rpgmaker
    fbneo: arcade
    fm7: fm-7
    fmtowns: fm-towns
    gameandwatch: g-and-w
    gamecom: game-dot-com
    gamecube: ngc
    gb2players: gb
    gba2players: gba
    gbc2players: gbc
    gzdoom: doom
    lcdgames: handheld-electronic-lcd
    mame: arcade
    mastersystem: sms
    megadrive: genesis-slash-megadrive
    megadrive-msu: genesis-slash-megadrive
    model2: arcade
    model3: arcade
    msx1: msx
    msx2+: msx2
    naomi: arcade
    naomi2: arcade
    neogeo: neogeoaes
    neogeocd: neo-geo-cd
    ngp: neo-geo-pocket
    ngpc: neo-geo-pocket-color
    oricatmos: oric
    pc88: pc-8800-series
    pc98: pc-9800-series
    pcengine: turbografx16--1
    pcenginecd: turbografx-16-slash-pc-engine-cd
    pcfx: pc-fx
    pet: cpet
    pokemini: pokemon-mini
    prboom: doom
    psx: ps
    pv1000: casio-pv-1000
    samcoupe: sam-coupe
    scv: epoch-super-cassette-vision
    sega32x: sega32
    snes-msu: snes
    supracan: super-acan
    thomson: thomson-mo5
    ti99: ti-99
    tic80: tic
    triforce: arcade
    tutor: tomy-tutor
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    x68000: sharp-x68000
    zmachine: z-machine
    zx81: sinclair-zx81
    zxspectrum: zxs
  versions: {}
