# This config file is compatible with the ES-DE Emulation Frontend
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed

exclude:
  roms:
    single_file:
      extensions:
        - "xml"
        - "txt"
      names:
        - "info.txt"
        - "metadata.txt"
        - "systeminfo.txt"
        - "psy.ggjud.iso"
        - "psy.ggjud.nfo"
    multi_file:
      names:
        - "roms"
        - "pfx"
        - "mlc01"
        - ".Trash*"

system:
  platforms:
    3do: "3do"
    n3ds: "3ds"
    amiga: "amiga"
    amigacd32: "amiga-cd32"
    android: "android"
    arcade: "arcade"
    astrocde: "astrocade"
    apfm1000: "apf"
    atarijaguarcd: "jaguarcd"
    atari800: "atari8bit"
    pv1000: "casio-pv-1000"
    crvision: "creativision"
    lcdgames: "handheld-electronic-lcd"
    atarijaguar: "jaguar"
    atarilynx: "lynx"
    macintosh: "mac"
    megaduck: "mega-duck-slash-cougar-boy"
    neogeocd: "neo-geo-cd"
    ngp: "neo-geo-pocket"
    ngpc: "neo-geo-pocket-color"
    neogeo: "neogeoaes"
    gc: "ngc"
    odyssey2: "odyssey-2-slash-videopac-g7000"
    palm: "palm-os"
    pc88: "pc-8800-series"
    pc98: "pc-9800-series"
    pcfx: "pc-fx"
    pokemini: "pokemon-mini"
    samcoupe: "sam-coupe"
    mastersystem: "sega-master-system"
    sega32x: "sega32"
    megacd: "segacd"
    sfc: "sfam"
    sg-1000: "sg1000"
    x68000: "sharp-x68000"
    ti99: "ti-99"
    trs-80: "trs-80"
    tg-cd: "turbografx-16-slash-pc-engine-cd"
    tg16: "turbografx16--1"
    vic20: "vic-20"
    videopac: "videopac-g7400"
    pc: "win"
    wonderswancolor: "wonderswan-color"
    zmachine: "z-machine"
    zx81: "zx80"
    zxspectrum: "zxs"
    naomi: "arcade"
    naomi2: "arcade"
    naomigd: "arcade"
