# This config file is compatible with Batocera or Retrobat-based set-ups
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names: []
filesystem: {}
system:
  platforms:
    adam: colecoadam
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacdtv: cdtv
    astrocde: astrocade
    apfm1000: apf
    archimedes: acorn-archimedes
    atari800: atari
    atomiswave: arcade
    bbc: bbcmicro
    c20: vic-20
    coco: trs-80-color-computer
    crvision: creativision
    easyrpg: rpgmaker
    fbneo: arcade
    fm7: fm-7
    gamecube: ngc
    gb2players: gb
    gba2players: gba
    gbc2players: gbc
    gzdoom: doom
    mame: arcade
    mastersystem: sms
    megadrive-msu: megadrive
    model2: arcade
    model3: arcade
    msx1: msx
    msx2+: msx2
    naomi: arcade
    naomi2: arcade
    neogeo: neogeoaes
    oricatmos: oric
    pcengine: turbografx16--1
    pcenginecd: turbografx-16-slash-pc-engine-cd
    pet: cpet
    prboom: doom
    pv1000: casio-pv-1000
    samcoupe: sam-coupe
    scv: epoch-super-cassette-vision
    snes-msu: snes
    thomson: thomson-mo5
    ti99: ti-99
    tic80: tic
    triforce: arcade
    tutor: tomy-tutor
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    zmachine: z-machine
    zxspectrum: zxs
  versions: {}
